/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vgmos
 */
public class Adelanto extends javax.swing.JFrame {

    /**
     * Creates new form trece
     */
    
    metodos m1 = new metodos();
    public String idAdelanto;    
    
    public Adelanto() {
        initComponents();
        setLocationRelativeTo(null);
        llenarcombos();
    }
    
    public void llenarcombos() {
        nombreCliente.setModel(m1.llenarCMBClientes());
    }
    
    public void llenarTablaAdelanto(DefaultTableModel modelo){
        tablaAdelanto.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechaPrestamoAdelanto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        psAdelanto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        montoAdelanto = new javax.swing.JTextField();
        nombreClienteAdelanto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        promotorAdelanto = new javax.swing.JTextField();
        fechaFinAdelanto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        montoAdelantoFecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdelanto = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtFechaSalienteAdelanto = new com.toedter.calendar.JDateChooser();
        txtFechaEntrnateAdelanto = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 20));

        fechaPrestamoAdelanto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fechaPrestamoAdelanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaPrestamoAdelantoActionPerformed(evt);
            }
        });
        jPanel2.add(fechaPrestamoAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, -1));

        jButton1.setText("Cargar Info.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 30));

        jLabel2.setText("Nombre: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        nombreCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 410, -1));

        jLabel3.setText("Fecha Ptmo.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));
        jPanel2.add(psAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 180, -1));

        jLabel4.setText("Monto:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel5.setText("Nombre Cliente:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        montoAdelanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoAdelantoActionPerformed(evt);
            }
        });
        jPanel2.add(montoAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 110, -1));

        nombreClienteAdelanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteAdelantoActionPerformed(evt);
            }
        });
        jPanel2.add(nombreClienteAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, -1));

        jLabel6.setText("Promotor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        promotorAdelanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotorAdelantoActionPerformed(evt);
            }
        });
        jPanel2.add(promotorAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, -1));

        fechaFinAdelanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFinAdelantoActionPerformed(evt);
            }
        });
        jPanel2.add(fechaFinAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 110, -1));

        jLabel7.setText("Fecha Fin:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 730, 10));

        jLabel8.setText("Fecha Saliente");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));
        jPanel2.add(montoAdelantoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 200, 30));

        jLabel9.setText("Monto");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 30));

        jButton2.setText("Grabar Adelanto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 140, 30));

        tablaAdelanto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAdelanto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAdelantoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAdelanto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 740, 180));

        jLabel10.setText("Fecha Entrante");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        txtFechaSalienteAdelanto.setDateFormatString("y-MM-d");
        jPanel2.add(txtFechaSalienteAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 200, 30));

        txtFechaEntrnateAdelanto.setDateFormatString("y-MM-d");
        jPanel2.add(txtFechaEntrnateAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 790, 470));

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 360, 50));

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 360, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre                   =           nombreCliente.getSelectedItem().toString();
        DefaultComboBoxModel modelo     =           m1.llenarCMBFechaPrestamo(nombre);
        this.fechaPrestamoAdelanto.setModel(modelo);
        String FechaInicioPrestamo      =           fechaPrestamoAdelanto.getSelectedItem().toString();
        String[] datosPrestamo          =           m1.buscarPrestamo(FechaInicioPrestamo,nombre);
        
        this.nombreClienteAdelanto.setText(datosPrestamo[0]);
        this.promotorAdelanto.setText(datosPrestamo[1]);
        this.montoAdelanto.setText(datosPrestamo[2]);
        this.fechaFinAdelanto.setText(datosPrestamo[3]);
        llenarTablaAdelanto(m1.showTabletAdelanto(nombre,FechaInicioPrestamo));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void montoAdelantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoAdelantoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoAdelantoActionPerformed

    private void nombreClienteAdelantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteAdelantoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteAdelantoActionPerformed

    private void promotorAdelantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotorAdelantoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promotorAdelantoActionPerformed

    private void fechaFinAdelantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFinAdelantoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinAdelantoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
        Date fechaEntrante =           txtFechaEntrnateAdelanto.getDate();
        Date fechaSaliente =           txtFechaSalienteAdelanto.getDate();
        
        
        String txtfechaEntranteAdelanto=m1.formatoFecha(fechaEntrante);
        String txtfechaSalienteAdelanto=m1.formatoFecha(fechaSaliente);
        
        
        
        String txtmontoAdelantoFecha    =           montoAdelantoFecha.getText();
        String nombre                   =           nombreCliente.getSelectedItem().toString();
        String FechaInicioPrestamo      =           fechaPrestamoAdelanto.getSelectedItem().toString();
        
        m1.agregarAdelanto(txtfechaEntranteAdelanto, txtfechaSalienteAdelanto, txtmontoAdelantoFecha,nombre,FechaInicioPrestamo);
        
        llenarTablaAdelanto(m1.showTabletAdelanto(nombre,FechaInicioPrestamo));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fechaPrestamoAdelantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaPrestamoAdelantoActionPerformed
        String nombre                   =           nombreCliente.getSelectedItem().toString();
        String FechaInicioPrestamo      =           fechaPrestamoAdelanto.getSelectedItem().toString();
        
        String[] datosPrestamo          =           m1.buscarPrestamo(FechaInicioPrestamo,nombre);
        
        this.nombreClienteAdelanto.setText(datosPrestamo[0]);
        this.promotorAdelanto.setText(datosPrestamo[1]);
        this.montoAdelanto.setText(datosPrestamo[2]);
        this.fechaFinAdelanto.setText(datosPrestamo[3]);
        
        
        llenarTablaAdelanto(m1.showTabletAdelanto(nombre,FechaInicioPrestamo));
    }//GEN-LAST:event_fechaPrestamoAdelantoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String idAdelanto=this.idAdelanto;
        m1.borrarAdelanto(idAdelanto);
        
        String nombre                   =           nombreCliente.getSelectedItem().toString();
        String FechaInicioPrestamo      =           fechaPrestamoAdelanto.getSelectedItem().toString();
        
        llenarTablaAdelanto(m1.showTabletAdelanto(nombre,FechaInicioPrestamo));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablaAdelantoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAdelantoMouseClicked
        int rowIndex = tablaAdelanto.getSelectedRow();
        Object value = tablaAdelanto.getValueAt(rowIndex, 0);
        String idAdelntao=value+"";
        this.idAdelanto=idAdelntao;
    }//GEN-LAST:event_tablaAdelantoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adelanto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaFinAdelanto;
    private javax.swing.JComboBox<String> fechaPrestamoAdelanto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField montoAdelanto;
    private javax.swing.JTextField montoAdelantoFecha;
    private javax.swing.JComboBox<String> nombreCliente;
    private javax.swing.JTextField nombreClienteAdelanto;
    private javax.swing.JTextField promotorAdelanto;
    private javax.swing.JTextField psAdelanto;
    private javax.swing.JTable tablaAdelanto;
    private com.toedter.calendar.JDateChooser txtFechaEntrnateAdelanto;
    private com.toedter.calendar.JDateChooser txtFechaSalienteAdelanto;
    // End of variables declaration//GEN-END:variables
}
