/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;
/**
 *
 * @author soldi
 */
public class Encargado extends javax.swing.JFrame {

    /**
     * Creates new form Encargado
     */
    
    metodos m1 = new metodos();

    public Encargado() {
        initComponents();
        setLocationRelativeTo(null);
        llenarcombos();
    }
    
    public void llenarcombos() {
        municipio.setModel(m1.llenarCMBMunicipio());
        supervisor.setModel(m1.llenarCMBSupervisor());
        buscarEncargado.setModel(m1.llenarCMBEncargado());
    }
    
    public void vaciarInputs(){
        encargado.setText("NULL");
        nombreEncargado.setText("");
        telefonoEncargado.setText("");
        direccionEncargado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscarEncargado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        encargado = new javax.swing.JTextField();
        nombreEncargado = new javax.swing.JTextField();
        telefonoEncargado = new javax.swing.JTextField();
        direccionEncargado = new javax.swing.JTextField();
        municipio = new javax.swing.JComboBox<>();
        supervisor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serach.png"))); // NOI18N
        jLabel2.setText("Buscar Encargado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        buscarEncargado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEncargadoActionPerformed(evt);
            }
        });
        jPanel1.add(buscarEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 170, -1));

        jLabel3.setText("Encargado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 20));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 20));

        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        jLabel7.setText("Municipio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, 20));

        jLabel8.setText("Supervisor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 20));

        encargado.setEditable(false);
        encargado.setText("NULL");
        jPanel1.add(encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, -1));
        jPanel1.add(nombreEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));
        jPanel1.add(telefonoEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, -1));
        jPanel1.add(direccionEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, -1));

        municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, -1));

        supervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 440, 90));

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jButton4.setText("CARGOS");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 40));

        jButton5.setText("ABONOS");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String txtnombreEncargado=nombreEncargado.getText();
        String txttelefonoEncargado=telefonoEncargado.getText();
        String txtdireccionEncargado=direccionEncargado.getText();
        String cmbmunicipio=municipio.getSelectedItem().toString();
        String cmbsupervisor=supervisor.getSelectedItem().toString();
        m1.agregarEncargado(txtnombreEncargado, txttelefonoEncargado, txtdireccionEncargado, cmbmunicipio, cmbsupervisor);
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (encargado.getText()!="NULL") {
            String txtEncargado=encargado.getText();
            String txtnombreEncargado=nombreEncargado.getText();
            String txttelefonoEncargado=telefonoEncargado.getText();
            String txtdireccionEncargado=direccionEncargado.getText();
            String cmbmunicipio=municipio.getSelectedItem().toString();
            String cmbsupervisor=supervisor.getSelectedItem().toString();
            m1.editarEncargado(txtnombreEncargado, txttelefonoEncargado, txtdireccionEncargado, cmbmunicipio, cmbsupervisor,txtEncargado);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un Supervisor");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEncargadoActionPerformed
        String[] datos=m1.filtrarEncargado(buscarEncargado.getSelectedItem().toString());
        encargado.setText(datos[0]);
        nombreEncargado.setText(datos[1]);
        telefonoEncargado.setText(datos[2]);
        direccionEncargado.setText(datos[3]);
    }//GEN-LAST:event_buscarEncargadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (encargado.getText()!="NULL") {
            String txtIDEncargado=encargado.getText();
            m1.borrarEncargado(txtIDEncargado);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un Supervisor");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buscarEncargado;
    private javax.swing.JTextField direccionEncargado;
    private javax.swing.JTextField encargado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> municipio;
    private javax.swing.JTextField nombreEncargado;
    private javax.swing.JComboBox<String> supervisor;
    private javax.swing.JTextField telefonoEncargado;
    // End of variables declaration//GEN-END:variables
}
