/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;
/**
 *
 * @author soldi
 */
public class Prestamista extends javax.swing.JFrame {

    /**
     * Creates new form Prestamista
     */
    
     metodos m1 = new metodos();
    
    public Prestamista() {
        initComponents();
        setLocationRelativeTo(null);
        llenarcombos();
    }
    
    public void llenarcombos() {
        municipio.setModel(m1.llenarCMBMunicipio());
        buscarPrestamista.setModel(m1.llenarCMBPrestamista());
    }
     
    public void vaciarInputs(){
        prestamista.setText("NULL");
        nombrePrestamista.setText("");
        telefonoPrestamista.setText("");
        direccionPrestamista.setText("");
        plaza.setText("");
        semanas.setText("");
        montoPrestamista.setText("");
        montoEspeciaPrestamista.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscarPrestamista = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prestamista = new javax.swing.JTextField();
        nombrePrestamista = new javax.swing.JTextField();
        telefonoPrestamista = new javax.swing.JTextField();
        direccionPrestamista = new javax.swing.JTextField();
        municipio = new javax.swing.JComboBox<>();
        plaza = new javax.swing.JTextField();
        semanas = new javax.swing.JTextField();
        montoPrestamista = new javax.swing.JTextField();
        montoEspeciaPrestamista = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serach.png"))); // NOI18N
        jLabel1.setText("Buscar Prestamista");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        buscarPrestamista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarPrestamista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPrestamistaActionPerformed(evt);
            }
        });
        jPanel1.add(buscarPrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 200, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 370, 10));

        jLabel2.setText("Prestamista");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel4.setText("Teléfono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel6.setText("Municipio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel7.setText("Plaza");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        jLabel8.setText("Semanas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        jLabel9.setText("Monto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        jLabel10.setText("Monto Especial");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        prestamista.setEditable(false);
        prestamista.setText("NULL");
        jPanel1.add(prestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));
        jPanel1.add(nombrePrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));
        jPanel1.add(telefonoPrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, 20));
        jPanel1.add(direccionPrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));

        municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioActionPerformed(evt);
            }
        });
        jPanel1.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, -1));
        jPanel1.add(plaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));
        jPanel1.add(semanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 200, -1));
        jPanel1.add(montoPrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 200, -1));
        jPanel1.add(montoEspeciaPrestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 200, -1));

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (prestamista.getText()!="NULL") {
            String txtprestamista=prestamista.getText();
            String txtnombrePrestamista=nombrePrestamista.getText();
            String txttelefonoPrestamista=telefonoPrestamista.getText();
            String txtdireccionPrestamista=direccionPrestamista.getText();
            String txtmunicipio=municipio.getSelectedItem().toString();
            String txtplaza=plaza.getText();
            String txtsemanas=semanas.getText();
            String txtmontoPrestamista=montoPrestamista.getText();
            String txtmontoEspeciaPrestamista=montoEspeciaPrestamista.getText();
            m1.editarEjecutivo(txtprestamista, txtnombrePrestamista,txttelefonoPrestamista,txtdireccionPrestamista,txtmunicipio,txtplaza,txtsemanas,txtmontoPrestamista,txtmontoEspeciaPrestamista);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un ejecutivo");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String txTnombrePrestamista=nombrePrestamista.getText();
        String txtTelefonoPrestamista=telefonoPrestamista.getText();
        String txtDireccionPrestamista=direccionPrestamista.getText();
        String txtMunicipio=municipio.getSelectedItem().toString();
        String txtPlaza=plaza.getText();
        String txtSemanas=semanas.getText();
        String txtMontoPrestamista=montoPrestamista.getText();
        String txtMontoEspeciaPrestamista=montoEspeciaPrestamista.getText();
        m1.agregarEjecutivo(txTnombrePrestamista, txtTelefonoPrestamista, txtDireccionPrestamista, txtMunicipio, txtPlaza, txtSemanas, txtMontoPrestamista, txtMontoEspeciaPrestamista);
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioActionPerformed

    private void buscarPrestamistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPrestamistaActionPerformed
        String[] datos=m1.filtrarEjecutivo(buscarPrestamista.getSelectedItem().toString());
        prestamista.setText(datos[0]);
        nombrePrestamista.setText(datos[1]);
        telefonoPrestamista.setText(datos[2]);
        direccionPrestamista.setText(datos[3]);
        plaza.setText(datos[5]);
        semanas.setText(datos[6]);
        montoPrestamista.setText(datos[7]);
        montoEspeciaPrestamista.setText(datos[8]);
    }//GEN-LAST:event_buscarPrestamistaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (prestamista.getText()!="NULL") {
            m1.borrarEjecutivo(prestamista.getText());
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un ejecutivo");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buscarPrestamista;
    private javax.swing.JTextField direccionPrestamista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField montoEspeciaPrestamista;
    private javax.swing.JTextField montoPrestamista;
    private javax.swing.JComboBox<String> municipio;
    private javax.swing.JTextField nombrePrestamista;
    private javax.swing.JTextField plaza;
    private javax.swing.JTextField prestamista;
    private javax.swing.JTextField semanas;
    private javax.swing.JTextField telefonoPrestamista;
    // End of variables declaration//GEN-END:variables
}
