/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;
/**
 *
 * @author soldi
 */
public class Supervisor extends javax.swing.JFrame {

    /**
     * Creates new form Supervisor
     */
   
    metodos m1 = new metodos();
    
    public Supervisor() {
        initComponents();
        setLocationRelativeTo(null);
        llenarcombos();
    }

    public void llenarcombos() {
        municipio.setModel(m1.llenarCMBMunicipio());
        prestamista.setModel(m1.llenarCMBPrestamista());
        buscarSupervisor.setModel(m1.llenarCMBSupervisor());
    }
    public void vaciarInputs(){
        supervisor.setText("NULL");
        nombreSupervisor.setText("");
        telefonoSupervisor.setText("");
        direccionSupervisor.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscarSupervisor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supervisor = new javax.swing.JTextField();
        nombreSupervisor = new javax.swing.JTextField();
        telefonoSupervisor = new javax.swing.JTextField();
        direccionSupervisor = new javax.swing.JTextField();
        municipio = new javax.swing.JComboBox<>();
        prestamista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serach.png"))); // NOI18N
        jLabel2.setText("Buscar Supervisor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        buscarSupervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSupervisorActionPerformed(evt);
            }
        });
        jPanel1.add(buscarSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, -1));

        jLabel1.setText("Supervisor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel3.setText("Nombre Supervisor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        jLabel4.setText("Teléfono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));

        jLabel6.setText("Municipio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel7.setText("Prestamista");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        supervisor.setEditable(false);
        supervisor.setText("NULL");
        supervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorActionPerformed(evt);
            }
        });
        jPanel1.add(supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 190, 20));
        jPanel1.add(nombreSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, 20));
        jPanel1.add(telefonoSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, 20));
        jPanel1.add(direccionSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, 20));

        municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 20));

        prestamista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(prestamista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 20));

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String txtnombreSupervisor=nombreSupervisor.getText();
        String txttelefonoSupervisor=telefonoSupervisor.getText();
        String txtdireccionSupervisor=direccionSupervisor.getText();
        String cmbmunicipio=municipio.getSelectedItem().toString();
        String cmbprestamista=prestamista.getSelectedItem().toString();
        m1.agregarSupervisor(txtnombreSupervisor, txttelefonoSupervisor, txtdireccionSupervisor, cmbmunicipio, cmbprestamista);
        vaciarInputs();
        llenarcombos();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void supervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (supervisor.getText()!="NULL") {
            String txtIDSupervisor=supervisor.getText();
            String txtNombreSupervisor=nombreSupervisor.getText();
            String txtTelefonoSupervisor=telefonoSupervisor.getText();
            String txtFireccionSupervisor=direccionSupervisor.getText();
            String cmbMunicipio=municipio.getSelectedItem().toString();
            String cmbPrestamista=prestamista.getSelectedItem().toString();
            m1.editarSupervisor(txtNombreSupervisor, txtTelefonoSupervisor, txtFireccionSupervisor, cmbMunicipio, cmbPrestamista,txtIDSupervisor);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un Supervisor");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (supervisor.getText()!="NULL") {
            String txtIDSupervisor=supervisor.getText();
            m1.borrarSupervisor(txtIDSupervisor);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione primero un Supervisor");
        }
        llenarcombos();
        vaciarInputs();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buscarSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSupervisorActionPerformed
        String[] datos=m1.filtrarSupervisor(buscarSupervisor.getSelectedItem().toString());
        supervisor.setText(datos[0]);
        nombreSupervisor.setText(datos[1]);
        telefonoSupervisor.setText(datos[2]);
        direccionSupervisor.setText(datos[3]);
    }//GEN-LAST:event_buscarSupervisorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buscarSupervisor;
    private javax.swing.JTextField direccionSupervisor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> municipio;
    private javax.swing.JTextField nombreSupervisor;
    private javax.swing.JComboBox<String> prestamista;
    private javax.swing.JTextField supervisor;
    private javax.swing.JTextField telefonoSupervisor;
    // End of variables declaration//GEN-END:variables
}
