/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vgmos
 */
public class trece extends javax.swing.JFrame {

    /**
     * Creates new form trece
     */
    
    metodos m1 = new metodos();
    
    public trece() {
        initComponents();
        setLocationRelativeTo(null);
        llenarcombos();
    }
    
    public void llenarcombos() {
        nombreCliente.setModel(m1.llenarCMBClientes());
    }
    
    public void llenarTablaTrece(DefaultTableModel modelo){
        tablaTrece.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechaPrestamoTrece = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        psTrece = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        montoTrece = new javax.swing.JTextField();
        nombreClienteTrece = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        promotorTrece = new javax.swing.JTextField();
        fechaFinTrece = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        fechaTrece = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrece = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 20));

        fechaPrestamoTrece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fechaPrestamoTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaPrestamoTreceActionPerformed(evt);
            }
        });
        jPanel2.add(fechaPrestamoTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, -1));

        jButton1.setText("Cargar Info.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 30));

        jLabel2.setText("Nombre: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        nombreCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 410, -1));

        jLabel3.setText("Fecha Ptmo.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));
        jPanel2.add(psTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 180, -1));

        jLabel4.setText("Monto:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel5.setText("Nombre Cliente:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        montoTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTreceActionPerformed(evt);
            }
        });
        jPanel2.add(montoTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 110, -1));

        nombreClienteTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteTreceActionPerformed(evt);
            }
        });
        jPanel2.add(nombreClienteTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, -1));

        jLabel6.setText("Promotor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        promotorTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotorTreceActionPerformed(evt);
            }
        });
        jPanel2.add(promotorTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, -1));

        fechaFinTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFinTreceActionPerformed(evt);
            }
        });
        jPanel2.add(fechaFinTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 110, -1));

        jLabel7.setText("Fecha Fin:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 710, 10));

        jLabel8.setText("Fecha trece");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));
        jPanel2.add(fechaTrece, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 30));
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 200, 30));

        jLabel9.setText("Monto");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 30));

        jButton2.setText("Grabar Trece");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 100, 30));

        tablaTrece.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTrece);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 740, 210));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre                   =           nombreCliente.getSelectedItem().toString();
        DefaultComboBoxModel modelo     =           m1.llenarCMBFechaPrestamo(nombre);
        this.fechaPrestamoTrece.setModel(modelo);
        String FechaInicioPrestamo      =           this.fechaPrestamoTrece.getSelectedItem().toString();
        String[] datosPrestamo          =           m1.buscarPrestamo(FechaInicioPrestamo,nombre);
        
        this.nombreClienteTrece.setText(datosPrestamo[0]);
        this.promotorTrece.setText(datosPrestamo[1]);
        this.montoTrece.setText(datosPrestamo[2]);
        this.fechaFinTrece.setText(datosPrestamo[3]);
        
        llenarTablaTrece(m1.showTabletTrece(nombre, FechaInicioPrestamo));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void montoTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTreceActionPerformed

    private void nombreClienteTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteTreceActionPerformed

    private void promotorTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotorTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promotorTreceActionPerformed

    private void fechaFinTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFinTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinTreceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String txtfechaTrece            =       fechaTrece.getText();
        String txtmonto                 =       monto.getText();
        String nombre                   =       nombreCliente.getSelectedItem().toString();
        String FechaInicioPrestamo      =       fechaPrestamoTrece.getSelectedItem().toString();
        m1.agregarTrece(txtfechaTrece, txtmonto, nombre, FechaInicioPrestamo);
        
        llenarTablaTrece(m1.showTabletTrece(nombre, FechaInicioPrestamo));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fechaPrestamoTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaPrestamoTreceActionPerformed
        String nombre                   =       nombreCliente.getSelectedItem().toString();
        String FechaInicioPrestamo      =       fechaPrestamoTrece.getSelectedItem().toString();
        
        String[] datosPrestamo          =           m1.buscarPrestamo(FechaInicioPrestamo,nombre);
        
        this.nombreClienteTrece.setText(datosPrestamo[0]);
        this.promotorTrece.setText(datosPrestamo[1]);
        this.montoTrece.setText(datosPrestamo[2]);
        this.fechaFinTrece.setText(datosPrestamo[3]);
        
        
        llenarTablaTrece(m1.showTabletTrece(nombre, FechaInicioPrestamo));
    }//GEN-LAST:event_fechaPrestamoTreceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trece().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaFinTrece;
    private javax.swing.JComboBox<String> fechaPrestamoTrece;
    private javax.swing.JTextField fechaTrece;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField montoTrece;
    private javax.swing.JComboBox<String> nombreCliente;
    private javax.swing.JTextField nombreClienteTrece;
    private javax.swing.JTextField promotorTrece;
    private javax.swing.JTextField psTrece;
    private javax.swing.JTable tablaTrece;
    // End of variables declaration//GEN-END:variables
}
